//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_B
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string GuardianName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
