//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbInfoPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbInfoPeriod()
        {
            this.DbInfoStatus = new HashSet<DbInfoStatu>();
        }
    
        public int DbInfoPeriodId { get; set; }
        public string DbInfoPeriod1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbInfoStatu> DbInfoStatus { get; set; }
    }
}
