//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbInfoStatu
    {
        public long DbInfoStatusId { get; set; }
        public Nullable<int> DbInfoTypeId { get; set; }
        public Nullable<int> DbInfoLoanId { get; set; }
        public Nullable<int> DbInfoPeriodId { get; set; }
        public Nullable<bool> DbInfoStatus { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual DbInfoPeriod DbInfoPeriod { get; set; }
        public virtual DbInfoType DbInfoType { get; set; }
    }
}
