//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.LoanDocuments = new HashSet<LoanDocument>();
            this.LoanCards = new HashSet<LoanCard>();
            this.DbInfoStatus = new HashSet<DbInfoStatu>();
        }
    
        public int LoanId { get; set; }
        public string LoanName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> DistributdedAmount { get; set; }
        public Nullable<System.DateTime> DistributdedDate { get; set; }
        public Nullable<System.DateTime> FirstDueDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> InterestPercentage { get; set; }
        public Nullable<decimal> EMIAmount { get; set; }
        public Nullable<decimal> NoOfDues { get; set; }
        public Nullable<int> RepaymentTypeId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDocument> LoanDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCard> LoanCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbInfoStatu> DbInfoStatus { get; set; }
    }
}
