//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_B
    {
        public int LoanId { get; set; }
        public string LoanName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> DistributdedAmount { get; set; }
        public Nullable<System.DateTime> DistributdedDate { get; set; }
        public Nullable<System.DateTime> FirstDueDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> InterestPercentage { get; set; }
        public Nullable<decimal> EMIAmount { get; set; }
        public Nullable<decimal> NoOfDues { get; set; }
        public Nullable<int> RepaymentTypeId { get; set; }
    }
}
