//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanCard
    {
        public int LoanCardId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public string LoanCardName { get; set; }
        public Nullable<int> DueNumber { get; set; }
        public Nullable<System.DateTime> PlannedCollectionDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ImpactTransValue { get; set; }
        public Nullable<decimal> NonImpactTransValue { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> PlannedCashAccount { get; set; }
        public Nullable<decimal> ActualCashAccount { get; set; }
        public Nullable<decimal> PlannedProfitAccount { get; set; }
        public Nullable<decimal> ActualProfitAccount { get; set; }
        public Nullable<System.DateTime> ActualCollectionDate { get; set; }
        public Nullable<bool> IsCollected { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
