//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDocuments_B
    {
        public int LoanDocumentsId { get; set; }
        public string AadhaarCardNumber { get; set; }
        public string AadhaarCardPath { get; set; }
        public Nullable<bool> IsAadhaarCardCollected { get; set; }
        public Nullable<int> LoanId { get; set; }
    }
}
