//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentType_B
    {
        public int RepaymentTypeId { get; set; }
        public string RepaymentTypeName { get; set; }
        public Nullable<bool> IsMonthBased { get; set; }
        public Nullable<bool> IsWeekBased { get; set; }
        public Nullable<bool> IsDaysBased { get; set; }
        public Nullable<int> DueCycleDays { get; set; }
    }
}
